config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  post '/users/login'

  get '/users/welcome'

  get 'blogs/index'

  get 'users/logout'

  resources :users

  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    #if a user is logged in,
    if !cookies[:user_id].nil?
      #set that user as the uer of the blog post being created
      @user = User.find(cookies[:user_id])
      @blog.user = @user
    else
      #otherwise dont allow the client to post new blogs
      flash[:blog_notice] = "You must be logged in to start blogging!"
      redirect_to '/blogs/index'
    end
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    if !cookies[:user_id].nil?
      @user = User.find(cookies[:user_id])
      @blog.user = @user
    end

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :message, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if !cookies[:user_id].nil?
      redirect_to '/users/welcome'
    else
      @users = User.all
      render :index
    end
  end

  #When the login button is clicked, the server sends info here
  def login
    #find the user from the database using the provided email and load into instance variable
    @user = User.find_by_email(params[:login_email])

    #if this user exists in our database
    if !@user.nil?
      #Then check if the login password matches the password from the database
      if @user.password == params[:login_password]
        #save the logged in user in a cookie
        cookies[:user_id] = @user.id
        #send the logged in user to the welcome page
        redirect_to '/users/welcome' and return
      #otherwise, if th epasswirds don;t match
      else
        #alert the user and send them back to log in
        flash[:pass_notice] = 'Invalid password! Try again.'
        redirect_to '/' and return
      end #end of password condition

      #otherwise, if the user doesnt exist in the database
    else
      #othewrwise alert the user and send them back to log in
      flash[:email_notice] = "Invalid email! Try again."
      render :index
    end #end of email condition

  end

  def welcome
    @user = User.find(cookies[:user_id])
  end

  def logout
    cookies.delete :user_id
    redirect_to '/'
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.message %></td>
        <td><%= blog.user.full_name %></td>
        <td><%= link_to 'Show', blog %></td>
        <td>
          <!-- Only show the edit and destroy option for blogs created by the logged in user. -->
          <% if !cookies[:user_id].nil? && cookies[:user_id].to_i == blog.user.id %>
            <%= link_to 'Edit', edit_blog_path(blog) %>
          <% end %>
         </td>
        <td>
          <% if !cookies[:user_id].nil? && cookies[:user_id].to_i == blog.user.id %>
            <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %> <br>

<h4><em><%= flash[:blog_notice] %></em></h4>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @blog.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog.user.full_name %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td>
          <!-- Only show edit and destroy user info option for the user thats logged in -->
          <% if !cookies[:user_id].nil? && cookies[:user_id].to_i == user.id%>
            <%= link_to 'Edit', edit_user_path(user) %>
          <% end %>
        </td>
        <td>
          <% if !cookies[:user_id].nil? && cookies[:user_id].to_i == user.id%>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<br>
<br>
<hr>
<br>

<% if !cookies.has_key?(:user_id) %>
  <h2>Log In:</h2><br>

  <form action="/users/login" method="post">
    Login Email: <br>
    <input type="text" name="login_email" placeholder="Email" required/> <br>
    Password: <br>
    <input type="password" name="login_password" placeholder="Password" required/> <br>
    <input type="submit" value="Log In" />
  </form>
<% else %>
  <a href="/users/logout">Log Out</a>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password.gsub(/[a-zA-Z]/, '*') %><br>
  <em>Lololol did you really think I would show you someone else's password??</em>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/welcome.html.erb
<h2> Welcome back, <%= @user.full_name %>!</h2>
<br>
<br>
<hr>
<br>
<hr>

<a href="/blogs/new">Start blogging!</a>

<p>
  <ul>
    <% @user.blogs.each do |blog| %>
    <li> <a href="/blogs/<%= blog.id %>"> <%= blog.title%> </a> </li>
    <% end %>
  </ul>
</p>

<a href="/users/logout">Log Out</a>